### ISSUE TITLE
Calling client.getProperties Returns Nothing

### ISSUE THREAD

**Issue by brandonhenry** [openstf/adbkit#114]
I'm trying to call getProperties on the device id that I get from listDevices and it keeps returning an empty object. I also tried client.shell command with getProp as the argument, but I'm still not getting anything. There are no errors or anything, just nothing is coming back.

Any ideas?

The device is an Oculus Quest if that helps

**Comment by sorccu** [comment]
Run `adb shell getprop` and see if that returns anything.

Also, show your code.

**Comment by brandonhenry** [comment]
`
export const getDevices = dispatch => {
  let deviceList = []

  client.listDevices()
    .then(function(devices) {
      devices.map((device)=>{deviceList.push(device)})
    })
    .then(() => {
      deviceList.forEach((device) => {
        client.getProperties(device.id)
        .then((properties) => {
          console.log(properties)
        })
      })
    })
}`

adb shell getprop returns values in the command line

**Comment by sorccu** [comment]
You’re not using promises properly. Do not use forEach, use Promise.map or similar. Just see the examples in the README. Also, check the same examples for the device list thing - you’re building your own list but you could’ve just used the original device list you received.
