### ISSUE TITLE
How can I exec commands as `root` user with this toolkit?

### ISSUE THREAD

**Issue by dickeylth** [openstf/adbkit#26]
Thank you for your work first!

Now I have rooted android devices, if I use `adb shell` under command-line and switched to `su`, I could access app data directories under `/data/data/com.xxx.xxx`, I want to know how I could switch to `root` user with this toolkit? For the moment I could only find the `client.shell(serial, command[, callback])` API, could you provide me some suggestions? Thank you!

**Comment by sorccu** [comment]
You don't need root for that. You can do `client.shell(<serial>, 'run-as org.example.myapp cat /data/data/org.example.myapp/some/file.txt')`.

If you really need `su`, you could probably format your command like this: `su - root -c "echo 1"`.
