### ISSUE TITLE
Error: spawn ENOENT

### ISSUE THREAD

**Issue by asadallahi** [openstf/adbkit#33]
I've got this error when trying to track the device: 
```
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
```
I've tested on another Maverics Macbook and it was fine.
I'm using MacBook Pro OSX Yosemite 10.10.5

**Comment by sorccu** [comment]
Maybe `adb` was not started or it was not in your `$PATH`?

**Comment by asadallahi** [comment]
yes it was for my ```$PATH```.
the ```$PATH``` to ```adb``` was wrong.

the problem solved. 
Thanks
