### ISSUE TITLE
client.shell returns inconsistent output

### ISSUE THREAD

**Issue by op1ekun** [openstf/adbkit#35]
Last time I asked my question about [object Object] being returned by client.shell:
https://github.com/openstf/adbkit/issues/34

The provided answer helped to correct my assumption, and fix the code.

However it seems that client.shell will returns either `Buffer` or `Stream` at it's convenience.
This causes code from the example (https://github.com/openstf/adbkit#example) to fail.
Please have a look at the excerpt from my code:

```
Unhandled rejection TypeError: undefined is not a function
    at Parser.readAll (c:\dev\playground\Reporter\node_modules\adbkit\lib\adb\parser.js:113:19)
    at module.exports.readAll (c:\dev\playground\Reporter\node_modules\adbkit\lib\adb\util.js:9:31)
    at tryCatcher (c:\dev\playground\Reporter\node_modules\bluebird\js\main\util.js:26:23)
    at Promise._settlePromiseFromHandler (c:\dev\playground\Reporter\node_modules\bluebird\js\main\promise.js:503:31)
    at Promise._settlePromiseAt (c:\dev\playground\Reporter\node_modules\bluebird\js\main\promise.js:577:18)
    at Promise._settlePromises (c:\dev\playground\Reporter\node_modules\bluebird\js\main\promise.js:693:14)
    at Async._drainQueue (c:\dev\playground\Reporter\node_modules\bluebird\js\main\async.js:123:16)
    at Async._drainQueues (c:\dev\playground\Reporter\node_modules\bluebird\js\main\async.js:133:10)
    at Immediate.Async.drainQueues [as _onImmediate] (c:\dev\playground\Reporter\node_modules\bluebird\js\main\async.js:15:14)
    at processImmediate [as _immediateCallback] (timers.js:367:17)
```

As I already mentioned in the previous issue I reported. The documentation suggests that a `Buffer` is returned by `client.shell`. However the code example later suggests that a `Stream` is returned. In fact both objects can be returned, and a developer need to cater for both of these scenarios.

I don't say it's a HARD BUG, but the behavior doesn't go well with the documentation. I already added an additional step in my code to work with `Buffer`/`Stream` output, but either fixing code (yeah sure) or documentation (more likely) will save people a lot of time :)

Thanks

**Comment by sorccu** [comment]
I agree that the documentation is wrong, we'll need to fix that. But I don't see how you would get either a buffer or a stream randomly... I just tried the example code as-is and it worked fine. Can you share some more details about your investigation?

**Comment by op1ekun** [comment]
Sure, I'm glad to help.

I call this code as a part of my device resilience subsystem:
```
client.shell(serial, 'ifconfig wlan0')
        .then(adbService.util.readAll)
        .then(function commandResult(result) {
            return result.toString()
        });
```

...and, as you've already suggested, it produces the error in a random way :(
I have no idea, maybe it's the command, maybe it's the device the thing is I randomly get a `Buffer` instead of a `Stream`.

I totally forgot to add my env data:
Version of adbkit: 2.3.1
Node: 0.10.40
System: Windows Server 2012 R2
Device: Nexus 7, Android 5.1.1

Other than that, GREAT JOB, this module saves lives ;)

**Comment by sorccu** [comment]
Might be worth trying with Node 0.12 or 4.x. We haven't tested 0.10 in a long time and there were some stream-related changes in 0.12 that I remember having to fix (although it could have been just that our code was bad). Also we've never tested anything on Windows... :)

Are you sure it really returns a buffer and not something else? Could you do `.then(function(really) { console.log('really?', really, typeof really) })` instead of readAll?

**Comment by sorccu** [comment]
Also, https://github.com/petkaantonov/bluebird/blob/master/API.md#promiselongstacktraces---void may or may not help a little in providing a more useful stack trace.

**Comment by op1ekun** [comment]
I will update my node to 0.12.7, and will check the `Buffer` hipothesis :)
Thanks!

**Comment by op1ekun** [comment]
So after one day of scrutinizing the code, and running test on real hardware there and back again, it seems that there was an issue with the old version of node.js.
The `0.12.7` version appears to be as stable as a solid rock.
Thanks for all the help :)

**Comment by joshuapinter** [comment]
It took me awhile to figure out how to use `readAll()` with Promises so I'm positing it here to help others: 

```js
const stream = await adbClient.shell( config.udid, "ime list -s" )
const result = await adb.util.readAll( stream );
console.log( result.toString() ); // => com.sec.android.inputmethod/.SamsungKeypad
```
