### ISSUE TITLE
Client side usage (e.g. with Browserify or Webpack) not functional

### ISSUE THREAD

**Issue by ddaaggeett** [openstf/adbkit#52]
Adbkit works fine running from a NodeJS server, but to run on the client side after running through Browserify, I get

`Uncaught TypeError: Cannot read property 'prototype' of undefined`

and I have no Idea how to get around this.

**Comment by sorccu** [comment]
I'm certainly open to a pull request, but I personally do not have a use case that requires Browserify or client side usage in general. I probably won't look into it until I do have one.

Please do let me know if you manage to get it working, though.

**Comment by ddaaggeett** [comment]
use case would be client commanding android device through client browser

**Comment by ddaaggeett** [comment]
i just discovered the STF project

**Comment by marksalpeter** [comment]
This interests me a lot. @sorccu, do you know why webpack is complaining or in general where to begin?
