### ISSUE TITLE
Support reverse command

### ISSUE THREAD

**Issue by nwalters512** [openstf/adbkit#56]
Although not in the official adb documentation, adb has a `reverse` command that functions similarly to `forward`; you can see the usage of the command with `adb --help`. It would be great to see adbkit support this feature.

**Comment by sorccu** [comment]
Yes that would definitely be great to have. I feel like it could probably be done mostly by copy pasting the forward implementation. Wanna try making a PR? :)

**Comment by nwalters512** [comment]
Guess it's about time that I learned CoffeeScript! I'll take a look later today.

**Comment by sorccu** [comment]
Some mystery guy, totally not you, has implemented this in #57 and it has been released in 2.7.0.
