### ISSUE TITLE
what we did in "adbkit usb-device-to-tcp"

### ISSUE THREAD

**Issue by WillPangZi** [openstf/adbkit#61]
Hi guys,
I want share local device to network, so I used adb forward to share the ports, like:
```
adb tcpip 5555
adb forward tcp:5555 tcp:5555
```
but the native adb forward only listen on localhost, so we use iptables to portmap the 5555 to another IPV4 port again.
finally we can access the device through STF, but the screen is very slow.

and when we use "adbkit usb-device-to-tcp" the screen is very fast, like native connected, can you share the principle how this command works.  
---because the source code is coffee script, and difficult for me...

**Comment by sorccu** [comment]
It just translates the ADB WIFI protocol to the USB protocol. I did a lot
of packet capturing to make it work as it was practically undocumented at
the time.

Also, ADB will listen on 0.0.0.0 if you start the ADB server with 'adb -a
-P 5037 server nodaemon'.

**Comment by WillPangZi** [comment]
Thanks for reply.
I tried use 
```
adb -a -P 5037 server nodaemon
adb tcpip 5555
adb forward tcp:15555 tcp:5555
```
and use the 15555 port directly, but the screen still slow, So it seems the problem is the efficiency of "adb forward" 

thanks, I will try another way to translate the ADB WIFI protocol.

**Comment by sorccu** [comment]
If you use 'adb tcpip' at all it will be slow. Adbkit pretends to be a
device in TCP mode but actually transkates everything to the USB protocol.
You cannot achieve the same with adb forward.
