### ISSUE TITLE
'device unauthorized' when use client.getProperties in tracker.on('add', cb)

### ISSUE THREAD

**Issue by ArvoGuo** [openstf/adbkit#63]
It catchs error:

```javascript
client.trackDevices()
    .then(function(tracker) {
      tracker.on('add', function(device) {
        console.log('add')
        client.getProperties(device.id, (err, properties) => {
          console.log(properties)
          })
          .catch(e => {
            console.log(e)
          })
      })
    })
    .catch(function(err) {
      console.error('Something went wrong:', err.stack)
    })

```

response is: 

`{ FailError: Failure: 'device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.'
`

but if I add setTimeout: 

```javascript
const adb = require('adbkit')
const client = adb.createClient()

  client.trackDevices()
    .then(function(tracker) {
      tracker.on('add', function(device) {
        console.log('add')
        setTimeout(() => {
          client.getProperties(device.id, (err, properties) => {
          console.log(properties)
          })
          .catch(e => {
            console.log(e)
          })
        }, 10000)
      })

    })
    .catch(function(err) {
      console.error('Something went wrong:', err.stack)
    })

```

it will get right response.

Is it necessary setTimeout to getProperties when tracker trigger event 'add' ?

**Comment by sorccu** [comment]
The add event includes the state (or type) of the device. It can be "device", "unauthorized" or "offline" (and some others if you're in bootloader mode). When a device is added, it may go through a few different states before becoming a "device" (meaning it's ready). This is the information we get from adb and it's your responsibility to to check that the state is what you need it to be.

**Comment by ArvoGuo** [comment]
thanks a lot.
