### ISSUE TITLE
How I can use sqlite3?

### ISSUE THREAD

**Issue by KovganIV** [openstf/adbkit#64]
After exec "sqlite3 FILE" I dont receive response. Can you give me advice?

**Comment by sorccu** [comment]
Need to see your code or we can't help you.

**Comment by KovganIV** [comment]
var Promise = require('bluebird');
var adb = require('adbkit');

var client = adb.createClient();

client.listDevices()
    .then(function(devices) {
        return Promise.map(devices, function(device) {
            return client.shell(device.id, 'sqlite3 /data/data/com.android.providers.settings/databases/settings.db')
                .then(adb.util.readAll)
                .then(function(output) {
                    console.log('[%s] %s', device.id, output.toString().trim())
                })
        })
    })
    .then(function() {
        console.log('Done.')
    })
    .catch(function(err) {
        console.error('Something went wrong:', err.stack)
    });

**Comment by sorccu** [comment]
Isn't that normal? If you run sqlite like that, it'll show something like:

```
SQLite version 3.9.2 2015-11-02 18:31:45
Enter ".help" for usage hints.
sqlite>
```

And now it's waiting for you to input a command. However, since you use `readAll()`, it's stuck waiting for the command to return, which it never does because you never give it anything to do. You need to remove `readAll()` and process the stream yourself.

**Comment by KovganIV** [comment]
Ok, I undarstand that. How I can send command to sqlite3 and get answer? For example ".tables". I need return table names to my nodejs code.
Can you paste example here?
![image](https://cloud.githubusercontent.com/assets/7087925/23648735/710e925e-034e-11e7-9c32-31c04f0c8688.png)

**Comment by sorccu** [comment]
No, I don't provide sqlite support. However, I would start by looking at `sqlite3 --help` and `man sqlite3`. It looks like you should be able to just give the command after the filename.

**Comment by KovganIV** [comment]
I dont understand how process stream myself and send command to sqlite3. It's main problem.

**Comment by KovganIV** [comment]
This is my final solution.
Thx for help, Sorccu. You were right about oneline command.

```
client.listDevices()
  .then(function(devices) {
    return Promise.map(devices, function(device) {
      return client.shell(device.id, 'sqlite3 /data/data/com.android.providers.settings/databases/settings.db "select * from secure where name=\'android_id\';"')
        .then(adb.util.readAll)
        .then(function(output) {
          console.log(output.toString())
        });
    })
  })
  .then(function() {
    console.log('Done.')
  })
  .catch(function(err) {
    console.error('Something went wrong:', err.stack)
  });
```

**Comment by sorccu** [comment]
Well that went better than expected, great! 👍
