### ISSUE TITLE
Update debug npm package to 2.6.3 to prevent nsp check to fail on adbkit

### ISSUE THREAD

**Issue by rpl** [openstf/adbkit#67]
Currently running `nsp check` on a project that depends from the last released version of adbkit (v. 2.7.1) fails because of a vulnerability detected for the npm package `ms` v. 0.7.0 (https://nodesecurity.io/advisories/46), which is included as a dependency by `debug` v. 2.1.3 (e.g. here is the error message from one of our travis builds: https://travis-ci.org/rpl/web-ext/jobs/212115440#L1234-L1237  

Note: I've tried to update `debug` to v. 2.6.3 (the last released version on npm) on a local clone of adbkit and running the test suite and it seems to work fine (and it also pass the `nsp check`).

**Comment by rpl** [comment]
btw, thanks a lot for adbkit! 
it is a very nice library for interacting with adb from a nodejs application (and it looks great used in combination with the async/await syntax).

**Comment by sorccu** [comment]
Thanks! Published as 2.7.2.
