### ISSUE TITLE
client.screencap maybe  has a bug at android 7.0

### ISSUE THREAD

**Issue by 0x88l** [openstf/adbkit#69]
I try to use adbkit's function of screencap. The core like this:
![image](https://cloud.githubusercontent.com/assets/18346467/25174842/3e4106dc-252b-11e7-86dc-8867d44e4c98.png)
The core work fine in other android version without huawei mate 9(android 7.0).
However,android 7.0 version screencap's photo  was broken.The reason is "photo to big"

**Comment by sorccu** [comment]
Can you show the exact error?

**Comment by 0x88l** [comment]
I haven't to read the code where it occured.
![image](https://cloud.githubusercontent.com/assets/18346467/25208152/41ac2bb0-25a5-11e7-818b-726228b5bcac.png)
The translation:
Windows Photo Viewer can not open this image because the file may be damaged, damaged, or too large

**Comment by sorccu** [comment]
Oh, I see. I think that's fixed in the latest adbkit actually.

**Comment by 0x88l** [comment]
What cause the problem,？Please tell me,thank you.

**Comment by sorccu** [comment]
So are you using the latest version?

**Comment by 0x88l** [comment]
The lasted version is ok.

**Comment by sorccu** [comment]
It's because 7.0 no longer transforms \n to \r\n. You can see the changes at https://github.com/openstf/adbkit/compare/v2.7.2...v2.8.1.
