### ISSUE TITLE
Is it possible to connect to adb server running remotely?

### ISSUE THREAD

**Issue by abhagupta** [openstf/adbkit#71]
I have a mac-mini which is connected to couple of android devices. I am trying to run connect to the  adb server running on this machine, so that I can run some tests on the devices using my local machine. Which means, I should be SSHing to the `adb` server running on MAC mini. I tried creating SSH tunnel and I could successfully do that. 

Now I want to try the same thing with `adbkit`. I see that while creating client, there is an `options`  object which has a `host` key. It obviously needs a SSH tunnel to access the host.... I am kinda lost here. Anyone has any ideas?

**Comment by sorccu** [comment]
Use environment variables to set them. I can't read the source code right
now but I believe you can use ADB_HOST and ADB_PORT. Try to look into those.

Note that not all functionality may work as you expect (e.g. port
forwarding).

**Comment by djimondev** [comment]
It seems to be a conception problem in my code.
I'm doing this:

```
client.trackDevices()
  .then(function(tracker) {
    tracker.on('add', function(device) {
        adbDeviceManager.addDevice(device.id);
        screen.update();
    })
    tracker.on('remove', function(device) {
        adbDeviceManager.updateDevice(device.id, enumAdbState.DISCONNECTED);
        screen.update();
    })
    tracker.on('end', function() {
        adbDeviceManager.reset();
        screen.update();
    })
  })
  .catch(function(err) {
    adbDeviceManager.reset();
    screen.update();
  });
```

And in my 'add' event the action is:

```
        client.install(device, this.apk)
          .then(function(device) {
            adbDeviceManager.updateDevice(device, enumAdbState.AUTHORIZED);
          })
          .catch(function(err) {
            console.error('Something went wrong:', err.stack)
            adbDeviceManager.updateDevice(device, enumAdbState.ERROR);
          })

```

But i think it doesn't work because of client is used in the same time to detect and upload .apk

**Comment by sorccu** [comment]
Please always define “it doesn’t work.” Are you getting an error? How do you know it’s not working? What should have happened, and what happened instead?

One thing I can think of is that when a device is added, it might not be usable immediately. Sometimes a device can appear in “offline” state and only become a “device” a bit later.

**Comment by djimondev** [comment]
Sorry, there has a problem with my browser...
My reply was about 'ADB_VENDOR_KEYS is not set'
I copy this in the good post...

**Comment by sorccu** [comment]
Seems this issue is no longer relevant.
