### ISSUE TITLE
ADB_VENDOR_KEYS is not set

### ISSUE THREAD

**Issue by djimondev** [openstf/adbkit#81]
Hello, 
I'm trying to push apk from my raspberry to an android device connected.
Everything is ok with detection but when i try to push apk, i got this error:

```
Something went wrong: FailError: Failure: 'device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.'
    at /home/pi/node_modules/adbkit/lib/adb/parser.js:183:29
    at tryCatcher (/home/pi/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/pi/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/pi/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/home/pi/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/pi/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/pi/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```

Could you please help me to fix that problem?
 - I can confirm that device is authorized (i can see that with adb devices)
 - I tried with adb kill-server that didn't fix anything.

Many thanks for you help,
Jim

**Comment by sorccu** [comment]
That error is reported directly by ADB, so I'm having a hard time believing that it's really authorized. You can try running your program with `DEBUG=adb:* node your-program-here.js` to see more output, not sure if that'll help though. It could also be that you originally started adb under another user (perhaps root), but then it died and got started up by adbkit again under a different user with no access to the root adbkey.

**Comment by djimondev** [comment]
Thx sorccu, I will try to restart my raspberry, double-check permissions and try `DEBUG=adb:* node your-program-here.js`. I keep you informed

**Comment by djimondev** [comment]
It seems to be a conception problem in my code.
I'm doing this:

```
client.trackDevices()
  .then(function(tracker) {
    tracker.on('add', function(device) {
        adbDeviceManager.addDevice(device.id);
        screen.update();
    })
    tracker.on('remove', function(device) {
        adbDeviceManager.updateDevice(device.id, enumAdbState.DISCONNECTED);
        screen.update();
    })
    tracker.on('end', function() {
        adbDeviceManager.reset();
        screen.update();
    })
  })
  .catch(function(err) {
    adbDeviceManager.reset();
    screen.update();
  });
```
And in my 'add' event the action is:

```
        client.install(device, this.apk)
          .then(function(device) {
            adbDeviceManager.updateDevice(device, enumAdbState.AUTHORIZED);
          })
          .catch(function(err) {
            console.error('Something went wrong:', err.stack)
            adbDeviceManager.updateDevice(device, enumAdbState.ERROR);
          })
```

But i think it doesn't work because of client is used in the same time to detect and upload .apk

**Comment by sorccu** [comment]
The `device` variable you get has two properties, `id` and `type`. The `type` field can be `offline`, `unauthorized`, `device` or some other rare value. It's possible that when a device gets added to adb, that it will briefly show up as `offline` or `unauthorized`. You should check the `type` to make sure the device is ready to accept commands (`type` needs to be `device`). You should also listen to the `change` event so that you can react when the device type changes.

**Comment by djimondev** [comment]
I'm having again the same problem using this : 

```
client.trackDevices()
  .then(function(tracker) {

    tracker.on('add', function(device) {
      console.log('Device %s was plugged in', device.id)
      console.log('Device is ', device.type)
      return client.install(device.id, apk)
    }).then(function() {
      console.log('Installed %s on all connected devices', apk)
    })
    .catch(function(err) {
      console.error('Something went wrong:', err.stack)
    })

    tracker.on('remove', function(device) {
      console.log('Device %s was unplugged', device.id)
    })
    tracker.on('end', function() {
      console.log('Tracking stopped')
    })
  })
  .catch(function(err) {
    console.error('Something went wrong:', err.stack)
  })

```
The response is:

```
Device ce051715a8960040057e was plugged in
Device is  offline
Unhandled rejection FailError: Failure: 'device unauthorized.
This adb server's $ADB_VENDOR_KEYS is not set
Try 'adb kill-server' if that seems wrong.
Otherwise check for a confirmation dialog on your device.'
    at /home/pi/node_modules/adbkit/lib/adb/parser.js:183:29
    at tryCatcher (/home/pi/node_modules/bluebird/js/main/util.js:26:23)
    at Promise._settlePromiseFromHandler (/home/pi/node_modules/bluebird/js/main/promise.js:503:31)
    at Promise._settlePromiseAt (/home/pi/node_modules/bluebird/js/main/promise.js:577:18)
    at Async._drainQueue (/home/pi/node_modules/bluebird/js/main/async.js:128:12)
    at Async._drainQueues (/home/pi/node_modules/bluebird/js/main/async.js:133:10)
    at Immediate.Async.drainQueues (/home/pi/node_modules/bluebird/js/main/async.js:15:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
```
I don't understand why my device seems to be offline...

With `adb devices`
I got this:

```
List of devices attached
ce051715a8960040057e	device
```

**Comment by sorccu** [comment]
Read what I said. When you connect a device, it will usually be in `offline` state for a brief moment. You can't see that by running the `adb devices` command manually because you're too slow, it's over in less than a second. STF receives a real-time stream of events from adb, which means that it's much faster than your fingers. And indeed, as confirmed by the log output, the device is `offline`. You need to wait until it's `device`.
