### ISSUE TITLE
Convert a "adb shell am start"

### ISSUE THREAD

**Issue by darkholiday** [openstf/adbkit#84]
hello i am trying to open an my app using deep-linking 
and i want to convert this command "./adb shell am start -a android.intent.action.VIEW -d "https://sample.com/sample" com.sample.sample" to run it in a node server any tips ? and thank you for this great work.

**Comment by sorccu** [comment]
Seriously, read the README... it’s right there.

**Comment by darkholiday** [comment]
hey u need to know that not everyone in here is an expert to figure out how this works.
i am a beginner so maybe some help on how to use this library may be appreciated i have tried to use client.startActivity(serial, options[, callback]) but i couldn't make it work 
can you please help me here and explain to me how to use it instead of "Seriously" and thanks.

**Comment by sorccu** [comment]
Similarly, my time is also valuable. Not only have I written the library for you, I’ve even documented it. It’s right there under startActivity. I will not write your code for you.

**Comment by darkholiday** [comment]
okay sorry for wasting your valuable time. but instead of writing that comment you could have helped me but you prefer to be arrogant. have a great day

**Comment by sorccu** [comment]
You will learn more by doing it yourself.
