### ISSUE TITLE
Push file failed

### ISSUE THREAD

**Issue by scottchejin** [openstf/adbkit#86]
I use push() to push a file to device. If the file name contains long Chinese chars, the name of the pushed file  will be changed.
client.push(device.id, '/media/data/download/' + fileName, '/data/local/tmp/'+"明月几时有把酒问青天.doc" )
the file on the device will be named:明月几时有把

**Comment by sorccu** [comment]
What’s your host OS?
What’s your OS’s charset?
What happens if you run adb push manually?

**Comment by scottchejin** [comment]
OS: 4.10.0-38-generic #42~16.04.1-Ubuntu
OS's charset:　en_US.UTF-8
The file upload successfully and the name is right when I run adb push  manually.

**Comment by koral--** [comment]
Fixed in https://github.com/openstf/adbkit/pull/127
