### ISSUE TITLE
Push lot of files on device causes Econnreset 

### ISSUE THREAD

**Issue by iabukai** [openstf/adbkit#88]
I need some help. I'm pushing bigger amount (153pcs) of files to my device.
I got an error on MAC OS. It's working properly on WINDOWS.

Unhandled rejection Error: connect ECONNRESET 127.0.0.1:5037
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)
Unhandled rejection Error: connect ECONNRESET 127.0.0.1:5037
    at Object._errnoException (util.js:1024:11)
    at _exceptionWithHostPort (util.js:1046:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1182:14)

Test code : 
```
var Promise = require('bluebird')
var adb = require('adbkit')
var apkReader = require('adbkit-apkreader')
var client = adb.createClient()
var apk = 'Sandbox.apk'
var device = {}
var path = require('path')
var klaw = require('klaw')
let promises = [];

client.listDevices().then((devices) => {
	console.log('Óha', devices)
	return _getFileListInDirectory('temp').then((files)=> {
		files.map((file) => {
			console.log('TRY TO PUSH FILE TO CLIENT ', file)
			client.push(devices[0].id, file, `/sdcard/folderondevice/${path.relative('temp', file).replace(/\\/g, '/')}`).then(
			(transfer) => promises.push(_checkTransferCompleted(transfer)))
		})
	})
})
	  
  let _checkTransferCompleted = (transfer) => {
    return new Promise((resolve, reject) => {
      transfer.on('end', resolve);
      transfer.on('error', reject);
    });
  }
  
  let _getFileListInDirectory = (directory) => {
    return new Promise((resolve, reject) => {
      let files = [];
      klaw(directory)
        .on('data', (item) => {
          if (!item.stats.isDirectory()) {
            files.push(item.path);
          }
        })
        .on('end', ()=> resolve(files))
        .on('error', (error) => reject(error));
    });
  }
```

DEBUG=*  is attached
 [debug.txt](https://github.com/openstf/adbkit/files/1514445/debug.txt)

**Comment by sorccu** [comment]
I think you should rewrite your code. Pushing 150+ files simultaneously doesn't seem like a great idea. Normally, you'd have some sort of a queue that ensures you only do up to N transfers at the same time. Note that doing that is good practice, not a dirty workaround.

I'm my opinion this isn't an issue with adbkit at all. I think that adb simply gets overwhelmed by the massive number of requests. You can take a closer look into adb's output by running `adb kill-server` to kill your currently running adb server, and then starting a new one with `ADB_TRACE=1 adb server nodaemon`. This should show a huge amount of information on stdout/stderr and might reveal the actual error.

**Comment by iabukai** [comment]
bluebird Promise.mapSeries could be a good workaround.
